// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/get-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { profile, education } from "npm:@/data/portfolio";
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get profile",
  description: "Return Prakhar Parashar's professional profile summary, headline, location, and education.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify({ profile, education }, null, 2) }],
    structuredContent: { profile, education }
  })
});

// src/lib/mcp/tools/list-skills.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { coreCompetencies, skillKeywords } from "npm:@/data/portfolio";
var list_skills_default = defineTool2({
  name: "list_skills",
  title: "List skills",
  description: "List Prakhar's core professional competencies with related keywords.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const skills = coreCompetencies.map((s) => ({ skill: s, keywords: skillKeywords[s] ?? [] }));
    return {
      content: [{ type: "text", text: JSON.stringify(skills, null, 2) }],
      structuredContent: { skills }
    };
  }
});

// src/lib/mcp/tools/list-experience.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { experience, careerTimeline } from "npm:@/data/portfolio";
var list_experience_default = defineTool3({
  name: "list_experience",
  title: "List work experience",
  description: "Return Prakhar's work experience entries and career timeline.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify({ experience, careerTimeline }, null, 2) }],
    structuredContent: { experience, careerTimeline }
  })
});

// src/lib/mcp/tools/list-projects.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { keyProjects } from "npm:@/data/portfolio";
var list_projects_default = defineTool4({
  name: "list_projects",
  title: "List key projects",
  description: "Return Prakhar's flagship RPA, SAP, and digital transformation projects.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(keyProjects, null, 2) }],
    structuredContent: { projects: keyProjects }
  })
});

// src/lib/mcp/tools/list-credentials.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { certifications, awards } from "npm:@/data/portfolio";
var list_credentials_default = defineTool5({
  name: "list_credentials",
  title: "List certifications and awards",
  description: "Return Prakhar's certifications and awards.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify({ certifications, awards }, null, 2) }],
    structuredContent: { certifications, awards }
  })
});

// src/lib/mcp/tools/submit-feedback.ts
import { createClient } from "npm:@supabase/supabase-js@^2.102.1";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var submit_feedback_default = defineTool6({
  name: "submit_feedback",
  title: "Submit feedback",
  description: "Leave feedback on Prakhar's portfolio as the signed-in user. Rating is 1-5.",
  inputSchema: {
    rating: z.number().int().min(1).max(5).describe("Rating from 1 to 5"),
    feedback_text: z.string().trim().max(2e3).optional().describe("Feedback message"),
    visitor_name: z.string().trim().max(120).optional(),
    visitor_company: z.string().trim().max(120).optional(),
    visitor_city: z.string().trim().max(120).optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("feedback").insert({
      rating: input.rating,
      feedback_text: input.feedback_text ?? null,
      visitor_name: input.visitor_name ?? ctx.getUserEmail() ?? null,
      visitor_company: input.visitor_company ?? null,
      visitor_city: input.visitor_city ?? null
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Feedback submitted (id: ${data.id})` }],
      structuredContent: { feedback: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "qnknctdfpvlnpxbgiepf";
var mcp_default = defineMcp({
  name: "prakhar-portfolio-mcp",
  title: "Prakhar Parashar Portfolio",
  version: "0.1.0",
  instructions: "Tools for exploring Prakhar Parashar's portfolio: profile, skills, work experience, key projects, and credentials. Authenticated users can submit feedback.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_profile_default, list_skills_default, list_experience_default, list_projects_default, list_credentials_default, submit_feedback_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
